repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    -   id: black
        args: ["--line-length", "120"]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/pylint-dev/pylint
    rev: v3.2.6
    hooks:
      - id: pylint
        language: system
        args:
          - "--ignore=alembic,__init__.py"
          - "--max-line-length=120"
          - "--disable=missing-docstring,no-member,missing-class-docstring,missing-function-docstring,missing-timeout,too-few-public-methods"
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: poetry.lock
