name: Check linters

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.8.1
          poetry install --no-root

      - name: Run isort
        run: |
          poetry run isort --check-only .

      - name: Run black
        run: |
          poetry run black --check .

      - name: Run pylint
        run: |
          poetry run pylint --recursive y .
