name: Build and test web application and database

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.8.1
          poetry install --no-root

      - name: Run docker compose and wait until web server is up
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
        run: |
          docker compose up --build -d

          docker ps

          docker compose logs db

          timeout 60 bash -c 'until docker compose exec db pg_isready; do sleep 1; done'

          timeout 60 bash -c 'until curl -s http://localhost:8000/health || curl -s http://localhost:8000; do sleep 1; done'

      - name: Run API tests
        run: poetry run pytest tests/test_api.py

      - name: Run database tests
        run: docker compose exec hackathon-starter-web-1 poetry run pytest tests/test_database.py

      - name: Stop and remove container
        run: docker compose down
