name: Build and test web application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t app .

      - name: Run Docker Container and wait until web server is up
        run: |
          docker run --name app_container -d -p 8000:8000 app
          timeout 60 bash -c 'until echo > /dev/tcp/localhost/8000; do sleep 1; done'

      - name: Run tests
        run: pytest tests/api.py

      - name: Stop and remove container
        run: |
          docker stop app_container
          docker rm app_container